POST http://127.0.0.1:3001/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "Debugging React applications using Chrome dev tools",
  "author": "Mir Ilham",
  "url": "httpswww.googleblogs.com",
  "likes": 100
}