@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY5MDcwNTE3MmQ3ZjM2NDc5MDRiYmUwYiIsImlhdCI6MTc2MjQxNjM3OH0.ZNlKwRzlafb_0FlX5QmuO5PYwJT2FvsC8sA6i-fDHb8
@blogId = 690c56d1e1607aa402032c06
DELETE http://127.0.0.1:3001/api/blogs/{{blogId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json